name: Auto Merge VPN Configs

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:        # Manual run option

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run merge script
        run: python super_merge.py

      - name: Commit & Push if changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add super_subscription.txt
          git diff --cached --quiet || git commit -m "Update super_subscription.txt"
          git push
